api:
  dashboard: True

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

http:
  middlewares:
    secureHeaders:
      headers:
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        stsSeconds: 31536000

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: fudless420@gmail.com
      storage: /certs/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

logLevel: DEBUG