services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    image: weed-backend:latest 
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - CONCURRENCY=2
    volumes:
      - ./static:/app/static/
      - ./media:/app/media/
    ports:
      - 8000:8000
  bot:
    image: weed-bot:latest
    container_name: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - backend
    env_file:
      - .env
  frontend:
    image: weed-front:latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 5173:5173

volumes:
  postgres: