# Generated by Django 5.1.1 on 2024-10-01 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления в базу"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения в базе"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("photo", models.ImageField(upload_to="", verbose_name="Иконка")),
                (
                    "imitate",
                    models.BooleanField(
                        default=False, verbose_name="Имитация проверки"
                    ),
                ),
                (
                    "seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Кол-во секунд, через которое будет активна кнопка 'Claim'",
                        verbose_name="Секунды",
                    ),
                ),
                ("text", models.CharField(verbose_name="Заголовок")),
                ("link", models.CharField(verbose_name="Ссылка")),
                ("reward", models.IntegerField(verbose_name="Награда")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TgChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления в базу"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения в базе"
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        help_text="Ссылка должна быть в формате @[name] и бот в администраторах",
                        verbose_name="Ссылка канала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
            },
        ),
        migrations.CreateModel(
            name="Complete",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления в базу"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения в базе"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "claimed",
                    models.BooleanField(default=False, verbose_name="Награда получена"),
                ),
                ("claimAt", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.tguser",
                        verbose_name="Юзер",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                        verbose_name="Таска",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="task",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                help_text="Должен быть выбран канал, либо включена имитация, иначе задания не будут засчитываться",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.tgchannel",
                verbose_name="ТГ канал",
            ),
        ),
    ]
