# Generated by Django 5.1.1 on 2024-10-17 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referrals",
            options={"verbose_name": "Реф", "verbose_name_plural": "Рефы"},
        ),
        migrations.RemoveField(
            model_name="tguser",
            name="lastClaim",
        ),
        migrations.AddField(
            model_name="referrals",
            name="summary",
            field=models.IntegerField(default=0, verbose_name="Сумма"),
        ),
        migrations.AddField(
            model_name="tguser",
            name="claimAt",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Следующий Claim",
            ),
            preserve_default=False,
        ),
    ]
