# Generated by Django 5.1.3 on 2024-12-10 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "createdAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления в базу"
                    ),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения в базе"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                ("image", models.ImageField(upload_to="", verbose_name="Картинка")),
            ],
            options={
                "verbose_name": "Монетка",
                "verbose_name_plural": "Монетки",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "Игра", "verbose_name_plural": "Игры"},
        ),
    ]
